<?php

return [
    'cnf_appname' => 'Cloud Tools',
    'cnf_appdesc' => 'Cloud Tools ERP System',
    'cnf_comname' => 'Cloud Tools',
    'cnf_email' => 'helpdesk@telecloud.co.za',
    'cnf_metakey' => 'my site , my company  , Larvel Crud',
    'cnf_metadesc' => 'Write description for your site',
    'cnf_group' => '10',
    'cnf_activation' => 'confirmation',
    'cnf_multilang' => '0',
    'cnf_lang' => 'en',
    'cnf_regist' => 'true',
    'cnf_front' => 'false',
    'cnf_recaptcha' => 'false',
    'cnf_theme' => 'sailor',
    'cnf_recaptchapublickey' => '',
    'cnf_recaptchaprivatekey' => '',
    'cnf_mode' => 'production',
    'cnf_logo' => 'backend-logo.png',
    'cnf_allowip' => '',
    'cnf_restrictip' => '192.116.134 , 194.111.606.21 ',
    'cnf_mail' => 'swift',
    'cnf_date' => 'Y-m-d',
];
